mkdir /home/build
cd /home/build
export DEBIAN_FRONTEND="noninteractive"
apt update && apt install -y wget unzip tar xz-utils git openjdk-8-jdk
wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
unzip *.zip
rm *.zip
wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.0-stable.tar.xz
tar xfv ./flutter_linux_1.22.0-stable.tar.xz
rm flutter_linux_1.22.0-stable.tar.xz
export PATH="$PATH:`pwd`/flutter/bin"
yes | ./tools/bin/sdkmanager --licenses
./tools/bin/sdkmanager --sdk_root=./tools --install "platform-tools" "platforms;android-29" "build-tools;29.0.2"

export PATH=$PATH:`pwd`/tools/bin:`pwd`/tools/platform-tools
ANDROID_SDK_ROOT=`pwd`/tools
ANDROID_HOME=`pwd`/tools
docker run --name flutter-build -v /home/pushpender/Documents/Projects/totp_flutter:/home/project -it ubuntu:20.04 bash
